version: '3.8'

services:
  demoapp:
    image: emotionevaluator/demoapp:1.0
    container_name: emotion-demo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mounts your current directory (for development)
    working_dir: /app
    command: python main.py
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1